#!/bin/bash

ulimit -n 51200 

pro="/etc/shadowsocks"
op="start"
ip=4

if [ $# -ne 1 -a $# -ne 2 ]; then
    echo "param num=$# is not valid!!"
    exit 1
fi

if [ "$1" = "off" ]; then
    op="stop"
elif [ "$1" = "res" ];  then
    op="restart"
fi

if [ "$2" = "6" ]; then
    ip=$2
fi
    
ssserver -c ${pro}${ip}'.json' -d $op
